[project]
name = "src"
version = "0.0.1"
description = "Loan_PayBack_Prediction"
authors = [{name = "Zafar Ali", email = "zafaralikhanfs45@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}